### PR TITLE
Fix svc-range invalid bug and support specified svc in load and scale command

### LINKED ISSUE #304: Flag svc-range is invalid in scale and load command
- Generate 5 services by kperf
```yaml
# config file
service:
  generate:
    number: 5
    interval: 1
    batch: 1
    concurrency: 1
    namespace: ktest
    svc-prefix: ktest
```

```bash
$ kperf service generate
Creating Knative Service ktest-1 in namespace test
Creating Knative Service ktest-0 in namespace test
Creating Knative Service ktest-2 in namespace test
Creating Knative Service ktest-3 in namespace test
Creating Knative Service ktest-4 in namespace test
```
- load in svc range 4,5
```yaml
# config file
service:
  namespace: ktest
  svc-prefix: ktest
  range: 4,5
  output: /tmp
  load:
    load-concurrency: 2
    load-duration: 2s
    verbose: true
```

```bash
$ kperf service load
2022/10/11 09:26:05 Namespace ktest, Service ktest-3, load start
2022/10/11 09:26:05 Namespace ktest, Service ktest-1, load start
2022/10/11 09:26:05 Namespace ktest, Service ktest-2, load start
2022/10/11 09:26:05 Namespace ktest, Service ktest-4, load start
2022/10/11 09:26:05 Namespace ktest, Service ktest-0, load start
```

As load and scale both use getService(), so we need to fix svc-range invalid bug in this function.

### PR DESCRIPTION
**Pull request by chzhyang**
# Changes

- `getServices()` gets existed services by specified svc or (svc-prefix + svcRange)
  - :bug: Fixed svc range invalid bug in `getService()` which is used by scale and load command 
  - :gift: Add svc flag in load and scale to support specified svc by user
- AS `getService()` and `ServicesToScale` struct are common function of scale and load, so moved them to common.go

Fixes #304

# Test 
- Generate 5 services(ktest-0 ... ktest-4) by kperf, then use kperf  to load svc range (4,5)
```yaml
# ~/.config/kperf/config.yaml
service:
  output: /tmp
  generate:
    number: 5
    interval: 1
    batch: 1
    concurrency: 1
    namespace: ktest
    svc-prefix: ktest
  load:
    load-concurrency: 2
    load-duration: 2s
    verbose: true
    namespace: ktest
    svc-prefix: ktest
    range: 4,5
```

```bash
$ kperf service generate
$ kperf service load
2022/10/12 01:33:06 Namespace ktest, Service ktest-4, load start
```
- Use kperf to load existed ksvc hello
```yaml
service:
   output: /tmp
   namespace: default
   svc: hello
   load:
     load-concurrency: 2
     load-duration: 2s
     verbose: true
```
```bash
$ kperf service load
2022/10/12 07:31:15 Namespace default, Service hello, load start
```

### CODE REVIEW

File: pkg/command/service/common.go [hunk 1]
```diff
@@ -93,6 +100,75 @@ func GetNamespaces(ctx context.Context, params *pkg.PerfParams, namespace, names
...
+		end, err := strconv.Atoi(r[1])
+		if err != nil {
+			return objs, err
+		}
+		if start >= 0 && end >= 0 && start <= end {
+			for i := start; i <= end; i++ {
+				svcRangeMap[fmt.Sprintf("%s-%d", svcPrefix, i)] = true
+			}
+		} else {
+			return objs, fmt.Errorf("failed to parse namespace range %s", svcRange)
```
Comment (psschwei) [inline pkg/command/service/common.go:126]:
```suggestion
			return objs, fmt.Errorf("failed to parse service range %s", svcRange)
```

File: pkg/command/service/common.go [hunk 2]
```diff
@@ -93,6 +100,75 @@ func GetNamespaces(ctx context.Context, params *pkg.PerfParams, namespace, names
 	return nsNameList, nil
 }
 
+// getServices gets existed services by svc or (svc-prefix, svcRange)
+func getServices(ctx context.Context, servingClient servingv1client.ServingV1Interface, nsNameList []string, service string, svcPrefix string, svcRange string) ([]ServicesToScale, error) {
```
Comment (psschwei) [inline pkg/command/service/common.go:104]: Since the old version of this was defined as:

```go
func getServices(ctx context.Context, servingClient servingv1client.ServingV1Interface, nsNameList []string, svcPrefix string)
```

should we append the new variables to the end (rather than inserting `service` before `svcPrefix`)?

File: pkg/command/service/common.go (hunk 1 above)
Comment (chzhyang) [reply pkg/command/service/common.go:126]: Thank you, will update

File: pkg/command/service/common.go (hunk 2 above)
Comment (chzhyang) [reply pkg/command/service/common.go:104]: Good idea. will address

**Review by psschwei — COMMENTED** [review]
/lgtm
