### PR TITLE
Refined test namespace check and readme

### LINKED ISSUE #7: Error: no namespace found with prefix test
If the specified namespaces does not exist, an error is reported as `Error: no namespace found with prefix test`.

```
$ kperf service generate -n 10 -b 2 -c 5 -i 5 --nsPrefix test --nsRange 1,3 --svcPrefix ktest --maxScale 1 --minScale 1
nsRangeMap: map[test-1:%!s(bool=true) test-2:%!s(bool=true) test-3:%!s(bool=true)]
DEBUG nsRangeMap: default
DEBUG nsRangeMap: ibm-cert-store
DEBUG nsRangeMap: ibm-operators
DEBUG nsRangeMap: ibm-system
DEBUG nsRangeMap: istio-system
DEBUG nsRangeMap: knative-eventing
DEBUG nsRangeMap: knative-serving
DEBUG nsRangeMap: ktest
DEBUG nsRangeMap: kube-node-lease
DEBUG nsRangeMap: kube-public
DEBUG nsRangeMap: kube-system
nsNameList: []

Error: no namespace found with prefix test
```
Could we make the namespaces created automatically if the specified namespaces don't exist?  Does that make sense to you? @zhanggbj

### LINKED ISSUE #13: Unable to run kperf with OpenShift
```
./kperf service generate -n 30 -b 10 -c 5 -i 15 --nsPrefix test --nsRange 1,3 --svcPrefix ktest --maxScale 1 --minScale 1
Error: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
Usage:
  kperf service generate [flags]

Flags:
  -b, --batch int          Number of ksvc each time to be created
  -c, --concurrency int    Number of multiple ksvcs to make at a time (default 10)
  -h, --help               help for generate
  -i, --interval int       Interval for each batch generation
      --maxScale int       For autoscaling.knative.dev/minScale
      --minScale int       For autoscaling.knative.dev/minScale
      --ns string          Namespace name. The ksvc will be created in the namespace
  -p, --nsPrefix string    Namespace prefix. The ksvc will be created in the namespaces with the prefix
      --nsRange string
  -n, --number int         Total number of ksvc to be created
      --svcPrefix string   ksvc name prefix. The ksvcs will be svcPrefix1,svcPrefix2,svcPrefix3...... (default "testksvc")
      --timeout duration   duration to wait for previous ksvc to be ready (default 10m0s)
      --wait               whether wait the previous ksvc to be ready

2020/11/17 09:34:07 failed to execute kperf command: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
```

### PR DESCRIPTION
**Pull request by zhanggbj**
# Changes

- Refine k8s namepace check for test
- Refine Readme

/kind bug
/kind documentation

Fixes #13 
Fixes #7 

**Release Note**

```release-note

```

**Docs**

```docs

```

### CODE REVIEW

File: pkg/command/service/generate.go [hunk 1]
```diff
@@ -75,51 +85,35 @@ kperf service generate —n 500 —interval 20 —batch 20 --min-scale 0 --max-s
...
+					return errors.Errorf("namespace %s not found, please create one", ns)
+				} else if err != nil {
+					return errors.Wrap(err, "failed to get namespace")
 				}
-			} else {
-				return fmt.Errorf("both ns and nsPrefix are empty")
 			}
+
+			restConfig, err := p.RestConfig()
+			ksvcClient, err = servingv1client.NewForConfig(restConfig)
```
Comment (gyohuangxin) [inline pkg/command/service/generate.go:112]: After I refine serving client initialization, you can use `ksvcClient, err := p.NewServingClient()` to avoid initial it again.

**Comment by maximilien** [comment]
Needs rebase...

File: README.md [hunk 2]
```diff
@@ -26,54 +26,56 @@ $ mv kperf /usr/local/bin/
...
+# Create a namespace for kperf to create Services in it
+kubectl create ns {namespace-name}
+
+# Create namespaces from test-1 to test-10 for kperf to create Services distributed in them
+for name in {1..10};do kubectl create ns test-$name;done
 ```
+
+### generate Knative Service deployment load
+```shell script
 # Generate total 30 knative service, for each 15 seconds create 10 ksvc with 5 concurrency in namespace test1, test2 and test3, and the ksvc names are ktest1, ktest2.....ktest29.
```
Comment (zyjiaobj) [inline README.md:47]: namespaces should be `test-1, test-2 and test-3`, and ksvc should be `ktest-0, ktest-1.....ktest-29`

File: README.md [hunk 3]
```diff
@@ -26,54 +26,56 @@ $ mv kperf /usr/local/bin/
...
 $ kperf service generate -n 30 -b 10 -c 5 -i 15 --nsPrefix test --nsRange 1,3 --svcPrefix ktest --maxScale 1 --minScale 1
```
Comment (zyjiaobj) [inline README.md:48]: According to the latest code:
`nsPrefix` => `namespace-prefix`
`nsRange` => `namespace-range`
`svcPrefix ` => `svc-prefix`
`minScale ` => `min-scale`
`maxScale ` => `max-scale`

File: README.md [hunk 4]
```diff
@@ -26,54 +26,56 @@ $ mv kperf /usr/local/bin/
...
+Creating ksvc ktest-1 in namespace test-2
 ...
 ...
-Creating ksvc ktestsss29 in namespace test3
-```
+Creating ksvc ktest-29 in namespace test-3
 ```
+
+```shell script
 # Generate total 30 knative service, for each 15 seconds create 10 ksvc with 1 concurrency in namespace test1, test2 and test3, and the ksvc names are ktest1, ktest2.....ktest29. The generation will wait the previous genreated service to be ready for most 10 seconds.
```
Comment (zyjiaobj) [inline README.md:58]: Same with the above.

File: README.md [hunk 5]
```diff
@@ -26,54 +26,56 @@ $ mv kperf /usr/local/bin/
...
 $ kperf service generate -n 30 -b 10 -c 5 -i 15 --nsPrefix test --nsRange 1,3 --svcPrefix ktest --wait --timeout 10s --maxScale 1 --minScale 1
```
Comment (zyjiaobj) [inline README.md:59]: Same with the above.

File: README.md [hunk 6]
```diff
@@ -26,54 +26,56 @@ $ mv kperf /usr/local/bin/
...
 - Overall Service Ready Measurement: time duration for Knative Service to be ready
+
+Here is a figure of different resources generated for a Knative Service(assuming Istio is the network solution).
 ![resources created by Knative Service](docs/service_creation.png)
 
 **Example 1 Measure Services (for eg. range 1,500)for load test under a specific namespace**
 
-```cassandraql
+```shell script
 $ kperf service measure -n ktest-1 --prefix ktest --range 101,110 --verbose
```
Comment (zyjiaobj) [inline README.md:79]: According to the latest code:
`prefix ` => `svc-prefix`

File: README.md [hunk 7]
```diff
@@ -145,6 +147,22 @@ $ cat /tmp/20200710182129_ksvc_creation_time.csv
   ktest-109,ktest-1,13,13,2,0,0,0,0,15,2,0,2,15
   ktest-110,ktest-1,14,13,1,0,0,0,0,18,3,0,3,18
 ```
+
+### Clean Knative Service generated for test
+```shell script
+# Delete all ksvc with name prefix ktest in namespaces with name prefix test and index 1,2,3
+$ kperf service clean --nsPrefix test --nsRange 1,3 --svcPrefix ktest
```
Comment (zyjiaobj) [inline README.md:154]: According to the latest code:
`nsPrefix` => `namespace-prefix`
`nsRange` => `namespace-range`
`svcPrefix ` => `svc-prefix`

File: pkg/command/service/generate.go (hunk 1 above)
Comment (zhanggbj) [reply pkg/command/service/generate.go]: @gyohuangxin Sure, will cover by a rebase.

File: README.md (hunk 2 above)
Comment (zhanggbj) [reply README.md]: @zyjiaobj nice catch! fixed

File: README.md (hunk 3 above)
Comment (zhanggbj) [reply README.md]: will cover by a rebase.

File: README.md (hunk 4 above)
Comment (zhanggbj) [reply README.md]: fixed!

File: README.md (hunk 7 above)
Comment (zhanggbj) [reply README.md:157]: fixed!

File: README.md (hunk 6 above)
Comment (zhanggbj) [reply README.md:82]: fixed!

File: README.md (hunk 5 above)
Comment (zhanggbj) [reply README.md]: svc-prefix

**Comment by zhanggbj** [comment]
Hi @gyohuangxin @zyjiaobj @maximilien @qibobo 
PR got rebased and comments addressed, please help to take a review. thanks!

**Comment by gyohuangxin** [comment]
LGTM

**Review by zyjiaobj — APPROVED** [review]
LGTM

File: pkg/command/service/generate.go [hunk 8]
```diff
@@ -69,50 +78,31 @@ kperf service generate —n 500 —-interval 20 —-batch 20 --min-scale 0 --max
...
-						}
-					}
-				} else {
-					for i := 0; i < len(nsList.Items); i++ {
-						if strings.HasPrefix(nsList.Items[i].Name, generateArgs.namespacePrefix) {
-							nsNameList = append(nsNameList, nsList.Items[i].Name)
-						}
-					}
+			// Check if namespace exists, in NOT, return error
+			for _, ns := range nsNameList {
```
Comment (qibobo) [inline pkg/command/service/generate.go:94]: If --namespace-prefix "test" --namespace-range is "1,3", but there are only test-1 and test-3, the old implementation can work but the new one can not.

Comment (qibobo) [reply pkg/command/service/generate.go:94]: And what about the same code snippet in clean?

**Review by gyohuangxin — APPROVED** [review]

File: pkg/command/service/generate.go (hunk 8 above)
Comment (zhanggbj) [reply pkg/command/service/generate.go:94]: @qibobo I'm thinking this is work as design, as described in the README, users should prepare the namespaces. For e.g., our test case is to distribute the service in 10 namespaces, test-1 to test-10, if test-2 to test-9 not working, the service will be disctributed to 2 namespaces, this will impact the test result due to autoscaler behavior, WDYT?

Comment (qibobo) [reply pkg/command/service/generate.go:94]: Make sense.

**Review by qibobo — APPROVED** [review]
/lgtm

File: pkg/command/service/generate.go (hunk 8 above)
Comment (zhanggbj) [reply pkg/command/service/generate.go:94]: For cleanup, i think the original works fine, if no namespace found, we can just skip

**Comment by zhanggbj** [comment]
Hi @maximilien, could you please help to review and merge it?
(usually a Knative member can merge PR if it is approved, not sure why it doesn't work here)

**Review by maximilien — APPROVED** [review]
Cool I would say address comments and let us know to LGTM

**Comment by maximilien** [comment]
@zhanggbj I believe the person has to have GH ID in the `owners` file to LGTM

**Comment by maximilien** [comment]
So right now for `kperf` is you, me, and TOC members. As the projects grows. Feel free to suggest new committers. Typically this means discussing with the current OWNERS (you and I) and nominating new ones. Once that’s done then we vote... so we need both you and I to agree and if not then TOC to break vote. Once voted then ask the nominee to submit PR to owners to add their ID and we would then merge. Feel free to suggest new committers when ready. Cheers 🥂

**Comment by zhanggbj** [comment]
@maximilien Sure, I think it's great to suggest new committers in the short future especially when they are actively contributing to this project:-) We can discuss this later, thanks!
